--FUNCION PARA MOSTRAR REGISTRO POR ID Y MOSTRAR SOLO LOS ACTIVOS
CREATE FUNCTION FN_Aula_SeleccionarPorId
(
	@NumeroAula VARCHAR(10)
)
RETURNS TABLE
AS
RETURN
	SELECT * FROM Aula
	WHERE NumeroAula = @NumeroAula
	AND Activo = 1